'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("JoomlaLibrary.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;JFormDataSet xmlns=&quot;http://tempuri.org/JFormDataSet.xsd&quot;&gt;
        '''  &lt;dataType&gt;
        '''    &lt;name&gt;int&lt;/name&gt;
        '''    &lt;type&gt;Integer&lt;/type&gt;
        '''    &lt;size&gt;20&lt;/size&gt;
        '''    &lt;filter&gt;intval&lt;/filter&gt;
        '''  &lt;/dataType&gt;
        '''  &lt;dataType&gt;
        '''    &lt;name&gt;boolean&lt;/name&gt;
        '''    &lt;type&gt;radio&lt;/type&gt;
        '''    &lt;validate&gt;boolean&lt;/validate&gt;
        '''  &lt;/dataType&gt;
        '''&lt;/JFormDataSet&gt;.
        '''</summary>
        Friend ReadOnly Property dataType() As String
            Get
                Return ResourceManager.GetString("dataType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;JFormDataSet xmlns=&quot;http://tempuri.org/JFormDataSet.xsd&quot;&gt;
        '''  &lt;type&gt;
        '''    &lt;type&gt;list&lt;/type&gt;
        '''    &lt;size&gt;1&lt;/size&gt;
        '''    &lt;validate&gt;options&lt;/validate&gt;
        '''  &lt;/type&gt;
        '''  &lt;type&gt;
        '''    &lt;type&gt;textarea&lt;/type&gt;
        '''    &lt;rows&gt;3&lt;/rows&gt;
        '''    &lt;cols&gt;30&lt;/cols&gt;
        '''  &lt;/type&gt;
        '''  &lt;type&gt;
        '''    &lt;type&gt;text&lt;/type&gt;
        '''    &lt;filter&gt;string&lt;/filter&gt;
        '''    &lt;size&gt;30&lt;/size&gt;
        '''  &lt;/type&gt;
        '''  &lt;type&gt;
        '''    &lt;type&gt;checkbox&lt;/type&gt;
        '''  &lt;/type&gt;
        '''  &lt;type&gt;
        '''    &lt;type&gt;checkboxes&lt;/type&gt;
        '''  &lt;/type&gt;
        '''  &lt;type&gt;
        '''    &lt;type&gt;category&lt;/typ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property type() As String
            Get
                Return ResourceManager.GetString("type", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
